
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-gauchoride-m23-9am-1
owner: ucsb-cs156-m23
repo_name: proj-gauchoride-m23-9am-1
pull_requests: [{"author":{"id":"U_kgDOBdDJ8w","is_bot":false,"login":"pabucsb","name":""},"headRefName":"Pablo-DriverDash","number":30,"title":"established placeholder for driver page","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/30"},{"author":{"id":"U_kgDOBdDJ8w","is_bot":false,"login":"pabucsb","name":""},"headRefName":"pablo-frontend-newfields","number":28,"title":"Made frontend changes to include new entity variables","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/28"},{"author":{"id":"MDQ6VXNlcjQwNzc1MzY0","is_bot":false,"login":"Aasish-Virjala","name":"Aasish Virjala"},"headRefName":"aasish-issue-14","number":23,"title":"Option for users to update their phone number in profile page","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/23"},{"author":{"id":"U_kgDOBdDJ8w","is_bot":false,"login":"pabucsb","name":""},"headRefName":"pablo-issue21","number":22,"title":"adjusted frontend to reflect changes to entity file","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/22"},{"author":{"id":"U_kgDOBdDJ8w","is_bot":false,"login":"pabucsb","name":""},"headRefName":"pablo-adjust-backend","number":19,"title":"adjusted backend and backend testing","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/19"},{"author":{"id":"MDQ6VXNlcjQwNzc1MzY0","is_bot":false,"login":"Aasish-Virjala","name":"Aasish Virjala"},"headRefName":"aasish-issue-13","number":17,"title":"Added PUT request and Mapping + Display Phone number on profile page","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/17"}]
