
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-gauchoride-m23-9am-1
owner: ucsb-cs156-m23
repo_name: proj-gauchoride-m23-9am-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjQwNzc1MzY0","is_bot":false,"login":"Aasish-Virjala","name":"Aasish Virjala"},"headRefName":"aasish-issue-66","number":67,"title":"Added RiderApplication Form, Stories, and Tests","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/67"},{"author":{"id":"U_kgDOBdDJ8w","is_bot":false,"login":"pabucsb","name":""},"headRefName":"Pablo-DisplayDash","number":65,"title":"Implemented driver dashboard page and dashboard page tests","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/65"},{"author":{"id":"MDQ6VXNlcjQwNzc1MzY0","is_bot":false,"login":"Aasish-Virjala","name":"Aasish Virjala"},"headRefName":"aasish-issue-58","number":64,"title":"Added DriverTable to DriverListPage","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/64"},{"author":{"id":"MDQ6VXNlcjQwNzc1MzY0","is_bot":false,"login":"Aasish-Virjala","name":"Aasish Virjala"},"headRefName":"aasish-issue-57","number":63,"title":"Created DriverTable component and storybook entry","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/63"},{"author":{"id":"MDQ6VXNlcjQwNzc1MzY0","is_bot":false,"login":"Aasish-Virjala","name":"Aasish Virjala"},"headRefName":"aasish-issue-56","number":62,"title":"Added navbar element for Drivers list and placeholder for Drivers Page @ /drivers","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/62"},{"author":{"id":"MDQ6VXNlcjQwNzc1MzY0","is_bot":false,"login":"Aasish-Virjala","name":"Aasish Virjala"},"headRefName":"aasish-issue-55","number":61,"title":"Added GET /api/drivers/all and DriverController + Tests","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/61"},{"author":{"id":"U_kgDOBdDJ8w","is_bot":false,"login":"pabucsb","name":""},"headRefName":"Pablo-RiderAppController","number":60,"title":"Created controller and controller tests for RiderApplication","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/60"}]
