
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-gauchoride-m23-9am-1
owner: ucsb-cs156-m23
repo_name: proj-gauchoride-m23-9am-1
pull_requests: [{"author":{"id":"U_kgDOBczuwQ","is_bot":false,"login":"adhit-s","name":""},"headRefName":"Adhit-PrivacyPlaceholder-2","number":52,"title":"Added placeholder for privacy policy page (& test) @ /privacy, and a link in the footer to it","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/52"},{"author":{"id":"U_kgDOBdDJ8w","is_bot":false,"login":"pabucsb","name":""},"headRefName":"Pablo-RiderApp-1","number":49,"title":"created data base record and fixtures","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/49"},{"author":{"id":"U_kgDOBczuwQ","is_bot":false,"login":"adhit-s","name":""},"headRefName":"Adhit-PrivacyFooter+HTML","number":45,"title":"Added footer link & actual privacy policy page HTML content","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/45"},{"author":{"id":"U_kgDOBnFUbw","is_bot":false,"login":"alecmorrison","name":""},"headRefName":"Alec-Shift-GetDriverShifts","number":39,"title":"Add Get all driver shifts method in Shift controller","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/39"},{"author":{"id":"U_kgDOBczuwQ","is_bot":false,"login":"adhit-s","name":""},"headRefName":"Adhit-RiderDashboard","number":31,"title":"Adhit rider dashboard","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/31"},{"author":{"id":"U_kgDOBdDJ8w","is_bot":false,"login":"pabucsb","name":""},"headRefName":"Pablo-DriverDash","number":30,"title":"established placeholder for driver page","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/30"},{"author":{"id":"MDQ6VXNlcjQwNzc1MzY0","is_bot":false,"login":"Aasish-Virjala","name":"Aasish Virjala"},"headRefName":"aasish-issue-14","number":23,"title":"Option for users to update their phone number in profile page","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-1/pull/23"}]
