name: "32-frontend-coverage: Frontend Coverage (JavaScript/Jest)"

on:
  workflow_dispatch:
  pull_request:
    paths: [frontend/**]
  push:
    branches: [main]
    paths: [frontend/**]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Los_Angeles"
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ./frontend
      - run: npm run coverage
        working-directory: ./frontend
      - name: Upload jest coverage report to Artifacts
        if: always() # always upload artifacts, even if tests fail
        uses: actions/upload-artifact@v2
        with:
          name: jest-coverage
          path: frontend/coverage/lcov-report/*
     
