name: "34-frontend-mutation-testing: Stryker JS Mutation Testing (JavaScript/Jest)"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [frontend/**]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Los_Angeles"
      - uses: actions/checkout@v3.5.2
        with: 
          fetch-depth: 2
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x
      - run: npm ci
        working-directory: ./frontend
      - run: npx stryker run
        working-directory: ./frontend
      - name: Upload stryker report to Artifacts
        if: always() # always upload artifacts, even if tests fail
        uses: actions/upload-artifact@v3.1.2
        with:
          name: stryker-report
          path: frontend/reports/mutation/html/*