# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: "40-check-production-build: Check Production Build (if this fails, deploying to Heroku will fail)"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Los_Angeles"
    - uses: actions/checkout@v3.5.2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      env:
        TEST_PROPERTIES: ${{ secrets.TEST_PROPERTIES }}
        PRODUCTION: true
      run: mvn -DskipTests clean dependency:list install

  
